spring.application.name=dentalClinic
spring.datasource.url=jdbc:postgresql://localhost:5432/dental_clinic
spring.datasource.username=postgres
spring.datasource.password=xush2004@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret.key="qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvtrghbtrbrtbntrnrtgwnwrnwnbnm"
jwt.expiration=3600000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xushnudbekvaxobov0421@gmail.com
spring.mail.password=oblv wzjm wwvz fkcb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.sql.init.mode=never